### ISSUE TITLE
save 'image/jpeg' displays as black box

### ISSUE THREAD

**Issue by stupax** [WangShayne/vue-signature#6]
When I use this.$refs.signature.save('image/jpeg') it renders as a black box.

**Comment by WangShayne** [comment]
fixed,thanks!

**Comment by stupax** [comment]
Nice one thanks

**Comment by stupax** [comment]
I have updated the vue-signature npm package to 1.6 but I am still seeing the issues, any ideas?

**Comment by WangShayne** [comment]
can you show me your code?
The issue is that when you want to save the 'image/jpeg', the background color must be opaque, so I set the default background color to white. I guess option is overwritten.

**Comment by WangShayne** [comment]
@stupax please help check version 1.6.1, thank you!🙏

**Comment by stupax** [comment]
Working now, thanks for the update

**Comment by stupax** [comment]
Thank you
